### ISSUE TITLE
Clone of test-jdo is not working

### ISSUE THREAD

**Issue by mores** [datanucleus/test-jdo#4]
Ubuntu 20.04.3 LTS

openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.14, vendor: Azul Systems, Inc., runtime: /usr/lib/jvm/zulu-11-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-1025-azure", arch: "amd64", family: "unix"

mvn clean compile test

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.957 s <<< FAILURE! - in org.datanucleus.test.SimpleTest
[ERROR] testSimple(org.datanucleus.test.SimpleTest)  Time elapsed: 0.89 s  <<< ERROR!
javax.jdo.JDOFatalUserException: A property named javax.jdo.PersistenceManagerFactoryClass must be specified, or a jar file with a META-INF/services/javax.jdo.PersistenceManagerFactory entry must be in the classpath, or a property named javax.jdo.option.PersistenceUnitName must be specified.
        at org.datanucleus.test.SimpleTest.testSimple(SimpleTest.java:17)
Caused by: javax.jdo.JDOFatalInternalException: Unexpected exception caught.
        at org.datanucleus.test.SimpleTest.testSimple(SimpleTest.java:17)
Caused by: java.lang.reflect.InvocationTargetException
        at org.datanucleus.test.SimpleTest.testSimple(SimpleTest.java:17)
Caused by: java.lang.NoClassDefFoundError: org/datanucleus/metadata/DatastoreIdentityMetaData
        at org.datanucleus.test.SimpleTest.testSimple(SimpleTest.java:17)
Caused by: java.lang.ClassNotFoundException: org.datanucleus.metadata.DatastoreIdentityMetaData
        at org.datanucleus.test.SimpleTest.testSimple(SimpleTest.java:17)

**Comment by andyjefferson** [comment]
mvn clean test

[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< org.datanucleus:datanucleus-test-jdo >----------------
[INFO] Building DataNucleus Test for JDO 6.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ datanucleus-test-jdo ---
[INFO] Deleting /home/andy/work/test-jdo-tmp (includes = [*.log, test.xls, test.ods, test.ooxml, test.xml], excludes = [])
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ datanucleus-test-jdo ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ datanucleus-test-jdo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/andy/work/test-jdo-tmp/target/classes
[INFO] 
[INFO] --- datanucleus-maven-plugin:6.0.0-m1:enhance (default) @ datanucleus-test-jdo ---
DataNucleus Enhancer (version 6.0.0.m5-SNAPSHOT) for API "JDO"
DataNucleus Enhancer completed with success for 1 classes.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ datanucleus-test-jdo ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/andy/work/test-jdo-tmp/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ datanucleus-test-jdo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/andy/work/test-jdo-tmp/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ datanucleus-test-jdo ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.datanucleus.test.SimpleTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.236 s - in org.datanucleus.test.SimpleTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.213 s
[INFO] Finished at: 2022-04-21T15:10:17+01:00
[INFO] ------------------------------------------------------------------------


Perhaps you should debug your Maven usage ... "mvn --debug" because it works for me. Clearly I have DN current codebase in my Maven local repo, but debugging your usage tells you where the problem with your environment is

**Comment by mores** [comment]
My environment is:
    mvn <--- artifactory <--- central maven repo
which is not working.

When I remove artifactory from the equation:
      mvn <--- central maven repo

This is building as expected.
